### ISSUE TITLE
Implement reinforcement learning roadmap

### ISSUE THREAD

**Issue by 0xsuu** [0xsuu/Project-Mahjong#134]
### Implement Route:
* Traditional Tabular Method:
  - [x] Monte Carlo Value Iteration on Tiny Mahjong ->
  - [x] Q-learning on Tiny Mahjong
* Learn the rules, learn the strategy:
  - [x] Tiny Mahjong ->
  - [ ] Simple Mahjong Random ->
  - [x] Gomoku Random ->
  - [ ] Simple Mahjong Greedy ->
  - [ ] Gomoku Beginner ->
  - [ ] Japanese Mahjong
* Learn to react:
  - [x] Breakout ->
  - [ ] Snake
* Self-playing:
  - [ ] Simple Mahjong Duel/Full ->
  - [ ] Japanese Mahjong
* Searching:
  - [ ] Tiny Mahjong (break the optimal) ->
  - [ ] Simple Mahjong ->
  - [ ] Japanese Mahjong
* Value prediction:
  - [ ] Tiny Mahjong ->
  - [ ] Simple Mahjong ->
  - [ ] Gomoku ->
  - [ ] Japanese Mahjong
